#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Create a program that drives the robot forward until the Ultrasound Sensor sees an object.
The robot then reacts differently depending of the distance of the object.
*/

task main()
{
	//Set motor speed at 50% (Drive Forwards).
	setMotorSpeed(motorB, 50);
	setMotorSpeed(motorC, 50);

	while (true){
	if getUSDistance(sonarSensor) < 10
	{
		//Set motor speed to 0% (Stop).
		setMotorSpeed(motorB, 0);
		setMotorSpeed(motorC, 0);
		
	}else if getUSDistance(sonarSensor) < 20
	{
	
	//Set motor speed to 10% .
		setMotorSpeed(motorB, 10);
		setMotorSpeed(motorC, 10);

	}
	else {
	
	//Set motor speed to 50% .
		setMotorSpeed(motorB, 50);
		setMotorSpeed(motorC, 50);

	}
	}
}